# Generated by Django 4.2.3 on 2023-07-27 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_coreuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoreUser',
            new_name='OrdinaryUser',
        ),
        migrations.AlterModelOptions(
            name='ordinaryuser',
            options={'verbose_name_plural': 'OrdinaryUser'},
        ),
    ]
