# Generated by Django 4.2.3 on 2023-07-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='hezhixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'hezhixin',
            },
        ),
    ]
