# Generated by Django 4.2.3 on 2023-07-31 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hezhixin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hezhixin',
        ),
    ]
