# Generated by Django 4.2.3 on 2023-07-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_coreuser_ordinaryuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinaryuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordinaryuser',
            name='photo',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
