# Generated by Django 4.2.3 on 2023-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ordinaryuser_birthday_alter_ordinaryuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinaryuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='ordinaryuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/'),
        ),
    ]
