# Generated by Django 4.2.3 on 2023-07-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ordinaryuser_photo_ordinaryuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordinaryuser',
            options={'verbose_name_plural': 'ordinaryuser'},
        ),
    ]
