# Generated by Django 4.2.3 on 2023-07-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordinaryuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinaryuser',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
