# Generated by Django 4.2.3 on 2023-08-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='团队简介'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams_logo/', verbose_name='团队logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, verbose_name='团队名称'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='组别')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='所属团队')),
            ],
        ),
    ]
