# Generated by Django 4.2.3 on 2023-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_team_description_alter_team_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinaryuser',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordinaryuser',
            name='email_verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordinaryuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
