[uwsgi]
socket          = 0.0.0.0:8000
chdir           = /var/www/MIS
wsgi-file       = MIS/wsgi.py
master          = true
processes       = 4
threads         = 5
vacuum          = true
buffer-size     = 8192
